app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')
    opinion = db.relationship('Opinion', backref='username', lazy='dynamic')


  
    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')


    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'        


class Role(db.Model):

    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Comments(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    opinion_id = db.Column(db.Integer, db.ForeignKey("opinion.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod

    def get_comment(cls,id):
        comments = Comments.query.filter_by(opinion=id).all()
        return comments
    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

class Opinion(db.Model):

    __tablename__ = 'opinion'

    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(255))
    
    opinion = db.Column(db.String(255))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
   

    def save_opinion(self):

        db.session.add(self)
        db.session.commit()
        
    @classmethod

    def get_opinion(cls,cate):

        opinion = Opinion.query.filter_by(category=cate).all()
        return opinion
        
    def __repr__(self):
        return f'Posts {self.title}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


class OpinionForm(FlaskForm):
    title = StringField('opinion Title')
   
    opinion = TextAreaField('opinion')
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

mail = Mail()
simple = SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Will add the views and forms
     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)
    

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)


from . import views,errors


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions

    bootstrap.init_app(app)
    # Registering the blueprint

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    
    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from app.models import *
from . import main
from .. import db,photos
from flask_login import login_required, current_user
import markdown2
from .forms import *
from .forms import UpdateProfile,OpinionForm,CommentForm
from ..request import getquote

@main.route('/')
def index():
    '''
    Index page
    return
    '''
    
    message= "Welcome to BLOG Application!!"
    title= 'BLOG-app!'
    result = Opinion.query.all()
    # print("our results",result)

    quote =getquote()


    return render_template('index.html', message=message,title=title , quote= quote, opinion = result) 

   


@main.route('/user/<uname>')
@login_required

def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required

def update_profile(uname):

    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required

def update_pic(uname):

    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))



@main.route('/comment/<id>')
@login_required

def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

@main.route('/opinion/', methods = ['GET','POST'])
@login_required

def new_opinion():


    quote = getquote()

    form = OpinionForm()
    
    if form.validate_on_submit():
        # category = form.category.data
        opinion= form.opinion.data
        title=form.title.data
        # Updated pitchinstance
        new_opinion= Opinion(title=title,opinion= opinion,user_id=current_user.id)
        title='New opinion'
        new_opinion.save_opinion()
        return redirect(url_for('main.new_opinion'))
    return render_template('opinion.html',form= form , quote = quote)

@main.route('/new_comment/<int:opinion_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(opinion_id):

    opinion = Opinion.query.filter_by(id = opinion_id).first()
    form = CommentForm()

    
        
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comments(comment=comment,user_id=current_user.id, opinion_id=opinion_id)
        new_comment.save_comment()
        return redirect(url_for('main.index'))


    title='New opinion'
    return render_template('new_comment.html',title=title,comment_form = form,opinion_id=opinion_id)

# @main.route('/category/<cate>')

# def category(cate):
#     '''
#     function to return the pitches by category
#     '''
#     category = Pitches.get_pitches(cate)
#     title = f'{cate}'
#     return render_template('categories.html',title = title, category = category)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}
{% endblock %}

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<body>
<div class="container">
  <div class="row">
    <div class="col-md-4 pt-3">
      <div class="card" style="position: relative">
        <div class="card-header">
          <div class="card-title">
            <h2>Quote of the day..</h2>
          </div>
        </div>
        <div class="card-body">
          <h2 class="quoted-author">{{ quote.author }}</h2>
          <p class="quoted-quote">{{ quote.quote }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
    <h3 class="text-center">COMMENTS </h2>
      {% for comm in comment[::-1] %}
      <div class="container">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-8">
            <div class="card-groups">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Commented by:~{{comm.username}}</h4>
                  <p class="card-text">{{comm.comment}}.</p>
                </div>
                <div class="card-footer bg-transparent border-success"><small>Publish
                    date:{{comm.date.strftime('%Y-%m-%d')}}</small></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/index.html
{% extends 'base.html'%}

{% import 'macros.html' as macro%}
{% import 'bootstrap/wtf.html' as wtf %}



{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content %}

<body>
  <div class="container-fluid">
    <div class="d-flex justify-content-center row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="card bg-dark">
          <div class="card-groups">
            <div class="card-body">
              <h5 class="qouted-qoute">{{quote.quote}}</h5>
              <p class="qouted-author">{{quote.author}}</p>
              <button type="button" class="btn btn-outline-primary"><a href="../opinion/">Enter a New blog</a></button>
            </div>


          </div>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
    <div class="row">
      {% for opinion in opinion %}
      <div class="card">
          <h4 class="opinion-title">{{opinion.opinion_title}}</h4>
          <h5 class="subtitle"> {{opinion.description}}</h5>
          <h6 class="opinion-name">Posted by ~ {{opinion.username}}</h6>
          <img src="{{ opinion.username.profile_pic_path }}" alt="">
          <p class="date text-muted">Posted on ~ {{opinion.date.strftime('%Y-%m-%d')}}</p>

          <button type="button" class="btn btn-outline-success btn-sm"><a
                  href="/new_comment/{{opinion.id}}"> Add Comment</a></button>
          <button type="button" class="btn btn-outline-success btn-sm"><a href="/comments/{{opinion.id}}">View
                  comment</a></button>


          
      </div>
      {%endfor%}
    </div>
  </div>

</body>
{% endblock%}

app/templates/macros.html
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.movie_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
    <nav>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogs</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
</head>
<body>
    <html>
<nav>
  <head>
    <meta charset="utf-8">
    <title>BLOG APP</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <styles>
  </styles>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
            <div class="navbar">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size:x-large; font-weight: bold; color:blue">BLOG APP</a>
              
      </div>
    </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li class="nav-item">
              <a class="nav-link nav-link-custom" href="{{ url_for('main.new_opinion') }}">OPINION</a>
            </li>
            
      </ul>
    

            <ul class="nav navbar-nav navbar-right">
               {% if current_user.is_authenticated %}
                   <li><a href="/" style="font-weight:bold;">{{current_user.username.capitalize()}} </a></li>
                   <li><a href="{{url_for('auth.logout')}}" style="color:blue;"><b>Sign out</b></a></li>
               {%else%}
                   <li><a href="{{url_for('auth.login')}}" style="color:blue;"><b>Sign in</b></a></li>
               {%endif%}
              
            </ul>
           
       </div>
  </div>
</div>
  </body>
</nav>
</html>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> 
{% endblock %}
{% block content %}
<body>
  <div class="container">
    <div class="row">
      <br> <hr> <br>
      <div class="col-md-3"></div>
      <div class="col-md-6"> 
        <h3 class="text-center" > <b>ADD A BLOG HERE</b></h3>
        
        {{ wtf.quick_form(comment_form) }}
      </div>  
      <div class="col-md-3"></div>
    </div>
  </div>
</body>
{% endblock %}

app/templates/opinion.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/index.css')}}">
{% endblock %}
{% block content %}

<body style="background-color:beige;">
    <br>
    <hr>
    <h3 class="text-center">BLOGS</h3>
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <div class="card-columns">

                    <div class="card  border-success">

                        <div class="card-body text">
                            <div class="card-body">
                                <h5 class="qouted-qoute">{{quote.quote}}</h5>
                                <p class="qouted-author">{{quote.author}}</p>

                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="banner-post-banner">
                                <div class="container" id="post-banner">
                                    <h2 class="text-center text-white">Add blog</h2>
                                    <p class="text-center text-white">Add your blog here..</p>

                                    {{ wtf.quick_form(form)}}
                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div>


          
        </div>

    </div>



</body>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
    </form>
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
   {% endif %}

  </div>

</div>

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %} 